Repository SANTOMY/PlaceIt, pull requests merged in 2021-06, with the labels that each got.

#208 既に登録されているemailでアカウントを作れないようにする
  front/src/components/Signup/Signup.vue
  front/src/routes/userRequest.js
Labels: bug

#209 [Bug] レビュー送信にはSpotIDしか使ってないのに，バックエンドではSpotNameを使って処理してる
  back/src/database/ReviewSQL.js
Labels: bug

#216 Fix search dialog bug
  front/src/components/Map/MapButtons/SearchDialog.vue
Labels: bug

#228 Feature/226 refine user profile UI
  front/src/components/UserProfile/SpotListCard.vue
  front/src/components/UserProfile/UserDelete.vue
  front/src/components/UserProfile/UserEdit.vue
  front/src/components/share/UserProfileDialog.vue
Labels: Front-End, bug

#230 スポット登録/更新後に正しくページ遷移しない
  front/src/components/Map/Map.vue
  front/src/components/SpotDetail/SpotDetail.vue
  front/src/components/SpotRegister/SpotRegister.vue
  front/src/components/UserProfile/SpotListCard.vue
Labels: bug, スポット
